kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: dingofs-sc-test-1
provisioner: csi.dingofs.com
allowVolumeExpansion: true
reclaimPolicy: Retain 
parameters:
  csi.storage.k8s.io/provisioner-secret-name: dingofs-secret-test-1
  csi.storage.k8s.io/provisioner-secret-namespace: dingofs
  csi.storage.k8s.io/node-publish-secret-name: dingofs-secret-test-1
  csi.storage.k8s.io/node-publish-secret-namespace: dingofs
  pathPattern: "${.pvc.namespace}-${.pvc.name}"
mountOptions:
  - fs.nocto_suffix=.ckpt
  - block_cache.cache_store=disk
  - disk_cache.cache_dir=/dingofs/client/data/cache/0;/dingofs/client/data/cache/1;/dingofs/client/data/cache/2
  - disk_cache.cache_size_mb=3145728   # 3T
  - disk_cache.drop_page_cache=true
  - data_stream.background_flush.interval_ms=10
  - data_stream.background_flush.trigger_force_memory_ratio=0.98
  - data_stream.file.flush_workers=8
  - data_stream.file.flush_queue_size=10000
  - data_stream.chunk.flush_workers=512
  - data_stream.chunk.flush_queue_size=10000
  - data_stream.slice.flush_workers=1024
  - data_stream.slice.flush_queue_size=10000
  - data_stream.page.total_size_mb=51200
  - s3.readCacheThreads=8
  - fs.kernelCache.attrTimeoutSec=3
  - fs.kernelCache.dirAttrTimeoutSec=3
  - fs.kernelCache.entryTimeoutSec=3
  - fs.kernelCache.dirEntryTimeoutSec=3
