apiVersion: v1
kind: Secret
metadata:
  name: dingofs-secret-test-1
  namespace: dingofs
  labels:
    dingofs.com/validate-secret: "true"
type: Opaque
stringData:
  name: "rados-fs-1"
  mdsAddr: "100.64.4.150:6700,100.64.4.151:6700,100.64.4.152:6700"
  storagetype: "rados"
  radosClustername: ""
  radosUsername: ""
  radosKey: ""
  radosMon: ""
  radosPoolname: ""
  quotaCapacity: "50" # GB
  quotaInodes: ""
