apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dingofs-pvc-test-1
  namespace: dingofs                      # namespace for PVC, could be different from PV
  labels:
    dc.com/osm.jspolicy.verify: "false"
  annotations:
    dingofs/mount-cpu-request: 32000m     # init request 32 cores
    dingofs/mount-cpu-limit: "64"         # max limit 64 cores
    dingofs/mount-memory-request: 50Gi    # init request 50Gi memory
    dingofs/mount-memory-limit: 60Gi      # max limit 60Gi memory
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
  volumeMode: Filesystem
  storageClassName: dingofs-sc-test-1
  selector:
    matchLabels:
      dingofs-name: dingofs-pv-1
