FROM harbor.zetyun.cn/dingofs/dingofs:v5.1-b1ec0f8
ADD bin/dingofs-csi-driver /usr/bin/dingofs-csi-driver
# ADD https://github.com/krallin/tini/releases/download/v0.19.0/tini-amd64 /bin/tini
COPY bin/tini-amd64 /bin/tini
RUN chmod +x /bin/tini
ENTRYPOINT [ "/bin/tini", "--", "/usr/bin/dingofs-csi-driver"]
