apiVersion: v1
data:
  config.yaml: |-
    enableNodeSelector: false
    mountPodPatch:
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: dingofs-csi-driver
    app.kubernetes.io/name: dingofs-csi-driver
    app.kubernetes.io/version: master
  name: dingofs-csi-driver-config
  namespace: dingofs
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: configmap-creator
  namespace: dingofs
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-creator-binding
  namespace: dingofs
subjects:
  - kind: ServiceAccount
    name: dingofs-csi-node-sa
    namespace: dingofs
roleRef:
  kind: Role
  name: configmap-creator
  apiGroup: rbac.authorization.k8s.io
