apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dingofs-dynamic-pvc
  namespace: dingofs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: dingofs-sc-s3