apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-1
  labels:
    dingofs-name: dongwei-k8s
spec:
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: csi.dingofs.com
    volumeHandle: fsname=dongwei-k8s;path=/dingofs/dongwei-k8s/data