apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc-1
  namespace: dingofs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  volumeName: local-pv-1
  storageClassName: ""