kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: dingofs-csi-node
  namespace: dingofs
spec:
  updateStrategy:
    type: OnDelete
  selector:
    matchLabels:
      app: dingofs-csi-node
  template:
    metadata:
      labels:
        app: dingofs-csi-node
    spec:
      serviceAccountName: dingofs-csi-service-account
      nodeSelector:
        dingofs-csi-node: enabled
      containers:
        - name: csi-node-driver-registrar
          image: quay.io/k8scsi/csi-node-driver-registrar:v1.3.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/csi.dingofs.com/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /registration
              name: registration-dir
        - name: dingofs-driver
          image: dingodatabase/dingofs-csi:v1.1
          imagePullPolicy: Always
          securityContext:
            privileged: true
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --nodeid=$(NODE_NAME)
            - --alsologtostderr
            - --v=5
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          lifecycle:
            preStop:
              exec:
                command: [
                  "/bin/sh", "-c",
                  "rm -rf /csi/csi.sock"
                ]
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /var/lib/kubelet
              mountPropagation: Bidirectional
              name: kubelet-dir
            - mountPath: /dfs
              mountPropagation: Bidirectional
              name: dingofs-dir
            - mountPath: /curvefs/client/data/cache/1
              mountPropagation: Bidirectional
              name: dingofs-diskcache-1
            - mountPath: /curvefs/client/data/cache/2
              mountPropagation: Bidirectional
              name: dingofs-diskcache-2
            - mountPath: /curvefs/client/data/cache/3
              mountPropagation: Bidirectional
              name: dingofs-diskcache-3
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi.dingofs.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: DirectoryOrCreate
          name: registration-dir
        - hostPath:
            path: /var/lib/kubelet
            type: Directory
          name: kubelet-dir
        - hostPath:
            path: /mnt/dingofs/volume
            type: DirectoryOrCreate
          name: dingofs-dir
        - hostPath:
            path: /mnt/dc-1
            type: Directory
          name: dingofs-diskcache-1
        - hostPath:
            path: /mnt/dc-2
            type: Directory
          name: dingofs-diskcache-2
        - hostPath:
            path: /mnt/dc-3
            type: Directory
          name: dingofs-diskcache-3

