kind: Deployment
apiVersion: apps/v1
metadata:
  name: dingofs-csi-controller
  namespace: dingofs
spec:
  selector:
    matchLabels:
      app: dingofs-csi-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: dingofs-csi-controller
    spec:
      serviceAccountName: dingofs-csi-service-account
      nodeSelector:
        dingofs-csi-controller: enabled
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: csi-provisioner
          image: quay.io/k8scsi/csi-provisioner:v1.6.0
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          args:
            - --provisioner=csi.dingofs.com
            - --csi-address=$(ADDRESS)
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: ADDRESS
              value: /csi/csi-controller.sock
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          # limits:
          #   cpu: 500m
          #   memory: 512Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
        - name: dingofs-driver
          image: dingodatabase/dingofs-csi:v1.1
          imagePullPolicy: Always
          securityContext:
            privileged: true
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --nodeid=$(NODE_NAME)
            - --alsologtostderr
            - --v=5
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: CSI_ENDPOINT
              value: unix:///csi/csi-controller.sock
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          lifecycle:
            preStop:
              exec:
                command: [
                  "/bin/sh", "-c",
                  "rm -rf /csi/csi-controller.sock"
                ]
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: /dfs
              mountPropagation: Bidirectional
              name: dingofs-dir
      volumes:
        - hostPath:
            path: /var/lib/kubelet/plugins/csi.dingofs.com
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: /mnt/dingofs/volume
            type: DirectoryOrCreate
          name: dingofs-dir

