kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: dingofs-sc
provisioner: csi.dingofs.com
allowVolumeExpansion: false
reclaimPolicy: Retain 
parameters:
  csi.storage.k8s.io/provisioner-secret-name: dingofs-secret
  csi.storage.k8s.io/provisioner-secret-namespace: dingofs
mountOptions:
  - diskCache.diskCacheType=2 # 2 for read and write, 1 for read only
  - block_cache.cache_store=disk # disk or none
  - disk_cache.cache_dir=/curvefs/client/data/cache/1:10240;/curvefs/client/data/cache/2:10240;/curvefs/client/data/cache/3:10240  # "/data1:100;/data2:200"
  - disk_cache.cache_size_mb=102400   # MB
