kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: dingofs-sc-1
provisioner: csi.dingofs.com
allowVolumeExpansion: false
reclaimPolicy: Retain
parameters:
  csi.storage.k8s.io/provisioner-secret-name: dingofs-secret-1
  csi.storage.k8s.io/provisioner-secret-namespace: dingofs
  csi.storage.k8s.io/node-publish-secret-name: dingofs-secret-1
  csi.storage.k8s.io/node-publish-secret-namespace: dingofs
mountOptions:
  - diskCache.diskCacheType=2
  - block_cache.cache_store=disk
  - disk_cache.cache_dir=/curvefs/client/data/cache/1:10240;/curvefs/client/data/cache/2:10240;/curvefs/client/data/cache/3:10240  # "/data1:100;/data2:200"
  - disk_cache.cache_size_mb=102400   # MB
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: dingofs-sc-2
provisioner: csi.dingofs.com
allowVolumeExpansion: false
reclaimPolicy: Retain
parameters:
  csi.storage.k8s.io/provisioner-secret-name: dingofs-secret-2
  csi.storage.k8s.io/provisioner-secret-namespace: dingofs
  csi.storage.k8s.io/node-publish-secret-name: dingofs-secret-2
  csi.storage.k8s.io/node-publish-secret-namespace: dingofs
mountOptions:
  - diskCache.diskCacheType=2
  - block_cache.cache_store=disk
  - disk_cache.cache_dir=/curvefs/client/data/cache/1:10240;/curvefs/client/data/cache/2:10240;/curvefs/client/data/cache/3:10240  # "/data1:100;/data2:200"
  - disk_cache.cache_size_mb=102400   # MB
