apiVersion: v1
kind: Pod
metadata:
  name: test-dingofs-app-1
  namespace: dingofs
spec:
  containers:
  - args:
    - -c
    - while true; do echo $(date -u) >> /data/out.txt; sleep 10; done
    command:
    - /bin/sh
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/centos:centos7.9.2009
    name: app
    volumeMounts:
    - mountPath: /data
      name: dingofs-pv
  volumes:
  - name: dingofs-pv
    persistentVolumeClaim:
      claimName: dingofs-pvc-1
---
apiVersion: v1
kind: Pod
metadata:
  name: test-dingofs-app-2
  namespace: dingofs
spec:
  containers:
  - args:
    - -c
    - while true; do echo $(date -u) >> /data/out.txt; sleep 10; done
    command:
    - /bin/sh
    image: swr.cn-north-4.myhuaweicloud.com/ddn-k8s/docker.io/centos:centos7.9.2009
    name: app
    volumeMounts:
    - mountPath: /data
      name: dingofs-pv
  volumes:
  - name: dingofs-pv
    persistentVolumeClaim:
      claimName: dingofs-pvc-2