apiVersion: v1
kind: PersistentVolume
metadata:
  name: static-pv-1
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: dingofs-sc
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: csi.dingofs.com
    volumeHandle: test-pv-1  # Unique identifier for the volume in the storage backend
    volumeAttributes:
       attribute1: value1