apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dingofs-pvc-1
  namespace: dingofs
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: dingofs-sc
